# Generated by Django 3.0.8 on 2020-07-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='semester',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
            ],
        ),
    ]
