# Generated by Django 3.0.8 on 2020-07-08 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.semester')),
            ],
        ),
        migrations.CreateModel(
            name='module',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField(max_length=255)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.subject')),
            ],
        ),
    ]
