# Generated by Django 3.0.8 on 2020-07-08 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_module_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='semester',
            new_name='sem',
        ),
    ]
